@startuml
skinparam packageStyle rectangle

package 契約 {
  object 契約 {
    契約ID
    容量プラン
    List<オプションプラン>
  }
}
note left of 契約
  契約ごとに容量プラン/オプションプランを選択する
  選択時にオプションプランの設定可能条件をチェックする

  契約で選択したプランに応じて請求金額を計算する
end note

package 容量プラン{
  object 容量プラン{
    容量プランID
    月額
  }
}
note bottom of 容量プラン
  プランは現在1G/3G/30Gある
  プランごとに月額が決まっている
end note
契約 "1" -d-> "1" 容量プラン

package オプションプラン{
  object オプションプラン{
    オプションプランID
    月額
  }
  object 設定可能容量プラン{
    List<許可容量プランID>
  }
  オプションプラン "1" *-- "0..1" 設定可能容量プラン
}
契約 "1" --> "0..n" オプションプラン
設定可能容量プラン "1" -r-> "0..n" 容量プラン
note bottom of 設定可能容量プラン
  オプションは設定できる容量プランが決まっている
  例：動画見放題オプションが設定できるのは、
  　　3Gプランと30Gプランのみ
end note

package 請求金額 {
  object 請求金額 {
    金額
  }
}
請求金額 <-r- 契約
@enduml
